services:
  pollapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - pollnet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - pollnet

networks:
  pollnet:
    driver: bridge