name: Build and Test with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker compose build --no-cache

      - name: Run containers
        run: |
          docker compose up -d
          sleep 10  # wait for services to start

      - name: Run basic health check
        run: |
          curl -f http://localhost:8080 || (docker compose logs && exit 1)

      - name: Tear down
        if: always()
        run: docker compose down -v